"""
Contains static champion data
"""

CHAMPIONS: dict[str, dict[str, int]] = {
    "Wukong": {"Gold": 1, "Board Size": 1},
    "Malphite": {"Gold": 1, "Board Size": 1},
    "Ao Shin": {"Gold": 8, "Board Size": 2},
    "Aphelios": {"Gold": 2, "Board Size": 1},
    "Aurelion Sol": {"Gold": 8, "Board Size": 2},
    "Bard": {"Gold": 5, "Board Size": 1},
    "Braum": {"Gold": 2, "Board Size": 1},
    "Corki": {"Gold": 4, "Board Size": 1},
    "Daeja": {"Gold": 7, "Board Size": 2},
    "Diana": {"Gold": 3, "Board Size": 1},
    "Elise": {"Gold": 3, "Board Size": 1},
    "Ezreal": {"Gold": 1, "Board Size": 1},
    "Gnar": {"Gold": 2, "Board Size": 1},
    "Hecarim": {"Gold": 4, "Board Size": 1},
    "Heimerdinger": {"Gold": 1, "Board Size": 1},
    "Idas": {"Gold": 7, "Board Size": 2},
    "Illaoi": {"Gold": 3, "Board Size": 1},
    "Jinx": {"Gold": 2, "Board Size": 1},
    "Karma": {"Gold": 1, "Board Size": 1},
    "Kayn": {"Gold": 2, "Board Size": 1},
    "Lee Sin": {"Gold": 3, "Board Size": 1},
    "Leona": {"Gold": 1, "Board Size": 1},
    "Lillia": {"Gold": 2, "Board Size": 1},
    "Lulu": {"Gold": 3, "Board Size": 1},
    "Nami": {"Gold": 2, "Board Size": 1},
    "Neeko": {"Gold": 4, "Board Size": 1},
    "Nidalee": {"Gold": 1, "Board Size": 1},
    "Nunu & Willump": {"Gold": 3, "Board Size": 1},
    "Olaf": {"Gold": 3, "Board Size": 1},
    "Ornn": {"Gold": 4, "Board Size": 1},
    "Pyke": {"Gold": 5, "Board Size": 1},
    "Qiyana": {"Gold": 2, "Board Size": 1},
    "Ryze": {"Gold": 3, "Board Size": 1},
    "Sejuani": {"Gold": 1, "Board Size": 1},
    "Senna": {"Gold": 1, "Board Size": 1},
    "Sett": {"Gold": 1, "Board Size": 1},
    "Shen": {"Gold": 2, "Board Size": 1},
    "Shi Oh Yu": {"Gold": 7, "Board Size": 2},
    "Shyvana": {"Gold": 8, "Board Size": 2},
    "Skarner": {"Gold": 1, "Board Size": 1},
    "Sona": {"Gold": 4, "Board Size": 1},
    "Soraka": {"Gold": 5, "Board Size": 1},
    "Swain": {"Gold": 7, "Board Size": 2},
    "Syfen": {"Gold": 7, "Board Size": 2},
    "Sylas": {"Gold": 3, "Board Size": 1},
    "Tahm Kench": {"Gold": 1, "Board Size": 1},
    "Talon": {"Gold": 4, "Board Size": 1},
    "Taric": {"Gold": 1, "Board Size": 1},
    "Thresh": {"Gold": 2, "Board Size": 1},
    "Tristana": {"Gold": 2, "Board Size": 1},
    "Twitch": {"Gold": 2, "Board Size": 1},
    "Varus": {"Gold": 3, "Board Size": 1},
    "Vladimir": {"Gold": 1, "Board Size": 1},
    "Volibear": {"Gold": 3, "Board Size": 1},
    "Xayah": {"Gold": 4, "Board Size": 1},
    "Yasuo": {"Gold": 5, "Board Size": 1},
    "Yone": {"Gold": 2, "Board Size": 1},
    "Zoe": {"Gold": 5, "Board Size": 1},
    "Zac": {"Gold": 2, "Board Size": 1},
    "Taliyah": {"Gold": 1, "Board Size": 1},
    "Graves": {"Gold": 4, "Board Size": 1},
    "Nasus": {"Gold": 1, "Board Size": 1},
    "Lux": {"Gold": 2, "Board Size": 1},
    "Nomsy": {"Gold": 6, "Board Size": 2},
    "Jax": {"Gold": 2, "Board Size": 1},
    "Nilah": {"Gold": 4, "Board Size": 1},
    "Pantheon": {"Gold": 4, "Board Size": 1},
    "Rakan": {"Gold": 3, "Board Size": 1},
    "Terra": {"Gold": 8, "Board Size": 2},
    "Rengar": {"Gold": 3, "Board Size": 1},
    "Seraphine": {"Gold": 3, "Board Size": 1},
    "Kaisa": {"Gold": 2, "Board Size": 1},
    "Zyra": {"Gold": 2, "Board Size": 1},
    "Zippy": {"Gold": 6, "Board Size": 2},
    "Jayce": {"Gold": 4, "Board Size": 1},
    "Sohm": {"Gold": 7, "Board Size": 2},
    "Rell": {"Gold": 2, "Board Size": 1},
    "Zeri": {"Gold": 3, "Board Size": 1}}
